name: UI Tests with OpenVPN

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Чтение кода из репозитория
        uses: actions/checkout@v4

      - name: Установка и подключение OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn
          
          echo "${{ secrets.OPENVPN_CONFIG }}" > client.ovpn
          echo "${{ secrets.OPENVPN_USER }}" > auth.txt
          echo "${{ secrets.OPENVPN_PASSWORD }}" >> auth.txt
          
          sudo openvpn --config client.ovpn --auth-user-pass auth.txt --daemon
          sleep 10

      - name: Проверка доступа к QA-домену
        run: |
          curl -I https://frontend.qa.profinansy.dev || echo "Домен доступен"

      - name: Настройка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Запуск Pytest на QA-стенде
        env:
          CI: "true"
          PROFINANSY_USER_EMAIL: ${{ secrets.QA_USER_EMAIL }}
          PROFINANSY_USER_PASSWORD: ${{ secrets.QA_USER_PASSWORD }}
        run: |
          pytest --domain=https://frontend.qa.profinansy.dev
